package net.renfei.dao.entity;

public class MenuDOWithBLOBs extends MenuDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_text
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    private String menuText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_link
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    private String menuLink;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_text
     *
     * @return the value of t_menu.menu_text
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public String getMenuText() {
        return menuText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu_text
     *
     * @param menuText the value for t_menu.menu_text
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public void setMenuText(String menuText) {
        this.menuText = menuText == null ? null : menuText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_link
     *
     * @return the value of t_menu.menu_link
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public String getMenuLink() {
        return menuLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu_link
     *
     * @param menuLink the value for t_menu.menu_link
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public void setMenuLink(String menuLink) {
        this.menuLink = menuLink == null ? null : menuLink.trim();
    }
}