package net.renfei.dao.entity;

public class MenuDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.id
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.pid
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.is_new_win
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    private Boolean isNewWin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.is_enable
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    private Boolean isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_type
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    private Integer menuType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.order_number
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    private Integer orderNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.id
     *
     * @return the value of t_menu.id
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.id
     *
     * @param id the value for t_menu.id
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.pid
     *
     * @return the value of t_menu.pid
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.pid
     *
     * @param pid the value for t_menu.pid
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.is_new_win
     *
     * @return the value of t_menu.is_new_win
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public Boolean getIsNewWin() {
        return isNewWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.is_new_win
     *
     * @param isNewWin the value for t_menu.is_new_win
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public void setIsNewWin(Boolean isNewWin) {
        this.isNewWin = isNewWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.is_enable
     *
     * @return the value of t_menu.is_enable
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.is_enable
     *
     * @param isEnable the value for t_menu.is_enable
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_type
     *
     * @return the value of t_menu.menu_type
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public Integer getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu_type
     *
     * @param menuType the value for t_menu.menu_type
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.order_number
     *
     * @return the value of t_menu.order_number
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.order_number
     *
     * @param orderNumber the value for t_menu.order_number
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }
}