package net.renfei.dao.entity;

public class PostsDOWithBLOBs extends PostsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_posts.featured_image
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    private String featuredImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_posts.title
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_posts.content
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_posts.source_url
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    private String sourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_posts.source_name
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    private String sourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_posts.describes
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    private String describes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_posts.keyword
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_posts.featured_image
     *
     * @return the value of t_posts.featured_image
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public String getFeaturedImage() {
        return featuredImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_posts.featured_image
     *
     * @param featuredImage the value for t_posts.featured_image
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public void setFeaturedImage(String featuredImage) {
        this.featuredImage = featuredImage == null ? null : featuredImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_posts.title
     *
     * @return the value of t_posts.title
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_posts.title
     *
     * @param title the value for t_posts.title
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_posts.content
     *
     * @return the value of t_posts.content
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_posts.content
     *
     * @param content the value for t_posts.content
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_posts.source_url
     *
     * @return the value of t_posts.source_url
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_posts.source_url
     *
     * @param sourceUrl the value for t_posts.source_url
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_posts.source_name
     *
     * @return the value of t_posts.source_name
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_posts.source_name
     *
     * @param sourceName the value for t_posts.source_name
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_posts.describes
     *
     * @return the value of t_posts.describes
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public String getDescribes() {
        return describes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_posts.describes
     *
     * @param describes the value for t_posts.describes
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public void setDescribes(String describes) {
        this.describes = describes == null ? null : describes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_posts.keyword
     *
     * @return the value of t_posts.keyword
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_posts.keyword
     *
     * @param keyword the value for t_posts.keyword
     *
     * @mbg.generated Thu Jun 06 13:14:39 CST 2019
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }
}