package net.renfei.dao.entity;

public class SettingDOWithBLOBs extends SettingDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.keys
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    private String keys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.values
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    private String values;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.keys
     *
     * @return the value of t_setting.keys
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    public String getKeys() {
        return keys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.keys
     *
     * @param keys the value for t_setting.keys
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    public void setKeys(String keys) {
        this.keys = keys == null ? null : keys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.values
     *
     * @return the value of t_setting.values
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    public String getValues() {
        return values;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.values
     *
     * @param values the value for t_setting.values
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    public void setValues(String values) {
        this.values = values == null ? null : values.trim();
    }
}