package net.renfei.dao.entity;

public class VAllInfoWithBLOBs extends VAllInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.title
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.featured_image
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    private String featuredImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.describes
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    private String describes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_allinfo.title
     *
     * @return the value of v_allinfo.title
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_allinfo.title
     *
     * @param title the value for v_allinfo.title
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_allinfo.featured_image
     *
     * @return the value of v_allinfo.featured_image
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public String getFeaturedImage() {
        return featuredImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_allinfo.featured_image
     *
     * @param featuredImage the value for v_allinfo.featured_image
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public void setFeaturedImage(String featuredImage) {
        this.featuredImage = featuredImage == null ? null : featuredImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_allinfo.describes
     *
     * @return the value of v_allinfo.describes
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public String getDescribes() {
        return describes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_allinfo.describes
     *
     * @param describes the value for v_allinfo.describes
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public void setDescribes(String describes) {
        this.describes = describes == null ? null : describes.trim();
    }
}