package net.renfei.dao.entity;

import java.util.Date;

public class VAllInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.type_id
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.cat_name
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    private String catName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.cat_ename
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    private String catEname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.category_id
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.id
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.release_time
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    private Date releaseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_allinfo.type_id
     *
     * @return the value of v_allinfo.type_id
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_allinfo.type_id
     *
     * @param typeId the value for v_allinfo.type_id
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_allinfo.cat_name
     *
     * @return the value of v_allinfo.cat_name
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public String getCatName() {
        return catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_allinfo.cat_name
     *
     * @param catName the value for v_allinfo.cat_name
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_allinfo.cat_ename
     *
     * @return the value of v_allinfo.cat_ename
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public String getCatEname() {
        return catEname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_allinfo.cat_ename
     *
     * @param catEname the value for v_allinfo.cat_ename
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public void setCatEname(String catEname) {
        this.catEname = catEname == null ? null : catEname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_allinfo.category_id
     *
     * @return the value of v_allinfo.category_id
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_allinfo.category_id
     *
     * @param categoryId the value for v_allinfo.category_id
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_allinfo.id
     *
     * @return the value of v_allinfo.id
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_allinfo.id
     *
     * @param id the value for v_allinfo.id
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_allinfo.release_time
     *
     * @return the value of v_allinfo.release_time
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_allinfo.release_time
     *
     * @param releaseTime the value for v_allinfo.release_time
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }
}