package net.renfei.www.entity.dbo;

import java.util.Date;

public class PageDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.id
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.category_id
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.views
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    private Long views;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.release_time
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    private Date releaseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.add_time
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.is_delete
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.id
     *
     * @return the value of t_page.id
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.id
     *
     * @param id the value for t_page.id
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.category_id
     *
     * @return the value of t_page.category_id
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.category_id
     *
     * @param categoryId the value for t_page.category_id
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.views
     *
     * @return the value of t_page.views
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public Long getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.views
     *
     * @param views the value for t_page.views
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public void setViews(Long views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.release_time
     *
     * @return the value of t_page.release_time
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.release_time
     *
     * @param releaseTime the value for t_page.release_time
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.add_time
     *
     * @return the value of t_page.add_time
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.add_time
     *
     * @param addTime the value for t_page.add_time
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.is_delete
     *
     * @return the value of t_page.is_delete
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.is_delete
     *
     * @param isDelete the value for t_page.is_delete
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}