package net.renfei.www.entity.dbo;

public class PageDOWithBLOBs extends PageDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.title
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.content
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.describes
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    private String describes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.keyword
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.title
     *
     * @return the value of t_page.title
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.title
     *
     * @param title the value for t_page.title
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.content
     *
     * @return the value of t_page.content
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.content
     *
     * @param content the value for t_page.content
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.describes
     *
     * @return the value of t_page.describes
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public String getDescribes() {
        return describes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.describes
     *
     * @param describes the value for t_page.describes
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public void setDescribes(String describes) {
        this.describes = describes == null ? null : describes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.keyword
     *
     * @return the value of t_page.keyword
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.keyword
     *
     * @param keyword the value for t_page.keyword
     *
     * @mbg.generated Wed Jun 05 18:24:36 CST 2019
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }
}