package net.renfei.www.entity.dbo;

public class SettingDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.id
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.orders
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    private Integer orders;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.id
     *
     * @return the value of t_setting.id
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.id
     *
     * @param id the value for t_setting.id
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.orders
     *
     * @return the value of t_setting.orders
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.orders
     *
     * @param orders the value for t_setting.orders
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }
}