package net.renfei.www.entity.dbo;

public class TypeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.id
     *
     * @mbg.generated Wed Jun 05 18:23:18 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.type_name
     *
     * @mbg.generated Wed Jun 05 18:23:18 CST 2019
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.uri_path
     *
     * @mbg.generated Wed Jun 05 18:23:18 CST 2019
     */
    private String uriPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.id
     *
     * @return the value of t_type.id
     *
     * @mbg.generated Wed Jun 05 18:23:18 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.id
     *
     * @param id the value for t_type.id
     *
     * @mbg.generated Wed Jun 05 18:23:18 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.type_name
     *
     * @return the value of t_type.type_name
     *
     * @mbg.generated Wed Jun 05 18:23:18 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.type_name
     *
     * @param typeName the value for t_type.type_name
     *
     * @mbg.generated Wed Jun 05 18:23:18 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.uri_path
     *
     * @return the value of t_type.uri_path
     *
     * @mbg.generated Wed Jun 05 18:23:18 CST 2019
     */
    public String getUriPath() {
        return uriPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.uri_path
     *
     * @param uriPath the value for t_type.uri_path
     *
     * @mbg.generated Wed Jun 05 18:23:18 CST 2019
     */
    public void setUriPath(String uriPath) {
        this.uriPath = uriPath == null ? null : uriPath.trim();
    }
}