package net.renfei.www.entity.vo;

import lombok.Data;

import java.util.Date;

@Data
public class AllInfoVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.type_id
     *
     * @mbg.generated Mon Jun 10 14:36:04 CST 2019
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.cat_name
     *
     * @mbg.generated Mon Jun 10 14:36:04 CST 2019
     */
    private String catName;
    private String catEname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.category_id
     *
     * @mbg.generated Mon Jun 10 14:36:04 CST 2019
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.id
     *
     * @mbg.generated Mon Jun 10 14:36:04 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.release_time
     *
     * @mbg.generated Mon Jun 10 14:36:04 CST 2019
     */
    private Date releaseTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.title
     *
     * @mbg.generated Mon Jun 10 14:36:04 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.featured_image
     *
     * @mbg.generated Mon Jun 10 14:36:04 CST 2019
     */
    private String featuredImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_allinfo.describes
     *
     * @mbg.generated Mon Jun 10 14:36:04 CST 2019
     */
    private String describes;

    private String href;
    private String catHref;
}
