package net.renfei.dao.persistences;

import java.util.List;
import net.renfei.dao.entity.MenuDO;
import net.renfei.dao.entity.MenuDOExample;
import net.renfei.dao.entity.MenuDOWithBLOBs;
import org.apache.ibatis.annotations.Param;

public interface MenuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    long countByExample(MenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    int deleteByExample(MenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    int insert(MenuDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    int insertSelective(MenuDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    List<MenuDOWithBLOBs> selectByExampleWithBLOBs(MenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    List<MenuDO> selectByExample(MenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    MenuDOWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") MenuDOWithBLOBs record, @Param("example") MenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") MenuDOWithBLOBs record, @Param("example") MenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    int updateByExample(@Param("record") MenuDO record, @Param("example") MenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    int updateByPrimaryKeySelective(MenuDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(MenuDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Jun 11 13:08:41 CST 2019
     */
    int updateByPrimaryKey(MenuDO record);
}