package net.renfei.dao.persistences;

import java.util.List;

import net.renfei.dao.entity.SettingDO;
import net.renfei.dao.entity.SettingDOExample;
import net.renfei.dao.entity.SettingDOWithBLOBs;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface SettingDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    long countByExample(SettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    int deleteByExample(SettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    int insert(SettingDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    int insertSelective(SettingDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    List<SettingDOWithBLOBs> selectByExampleWithBLOBs(SettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    List<SettingDO> selectByExample(SettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    SettingDOWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") SettingDOWithBLOBs record, @Param("example") SettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SettingDOWithBLOBs record, @Param("example") SettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    int updateByExample(@Param("record") SettingDO record, @Param("example") SettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    int updateByPrimaryKeySelective(SettingDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(SettingDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated Thu Jun 06 16:20:08 CST 2019
     */
    int updateByPrimaryKey(SettingDO record);

    @Select("select * from t_setting where `keys` = #{keys,jdbcType=LONGVARCHAR} ORDER BY orders ASC")
    List<SettingDOWithBLOBs> selectByKeys(@Param("keys") String keys);
}