package net.renfei.dao.persistences;

import java.util.List;
import net.renfei.dao.entity.VAllInfo;
import net.renfei.dao.entity.VAllInfoExample;
import net.renfei.dao.entity.VAllInfoWithBLOBs;
import org.apache.ibatis.annotations.Param;

public interface VAllInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_allinfo
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    long countByExample(VAllInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_allinfo
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    int deleteByExample(VAllInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_allinfo
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    int insert(VAllInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_allinfo
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    int insertSelective(VAllInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_allinfo
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    List<VAllInfoWithBLOBs> selectByExampleWithBLOBs(VAllInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_allinfo
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    List<VAllInfo> selectByExample(VAllInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_allinfo
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") VAllInfoWithBLOBs record, @Param("example") VAllInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_allinfo
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") VAllInfoWithBLOBs record, @Param("example") VAllInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_allinfo
     *
     * @mbg.generated Mon Jun 10 18:10:20 CST 2019
     */
    int updateByExample(@Param("record") VAllInfo record, @Param("example") VAllInfoExample example);
}